# Generated by Django 5.0 on 2024-01-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_cart_cartitem_flavor_flavorimage_image_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttoimage',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='producttoimage',
            name='product_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ordertoproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='flavor',
            name='product',
            field=models.ManyToManyField(to='ecom.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='ecom.OrderToProduct', to='ecom.product'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urls', models.ImageField(upload_to='static/products/%y/%m/%d')),
                ('type', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProductToImage',
        ),
    ]
