# Generated by Django 5.0 on 2024-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_flavorimage_img_alter_productimages_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorimage',
            name='img',
            field=models.ImageField(upload_to='flavors/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='urls',
            field=models.ImageField(upload_to='products/%y/%m/%d'),
        ),
    ]
