# Generated by Django 5.0 on 2024-01-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_alter_flavorimage_img_alter_productimages_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetso', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='flavorimage',
            name='flavor',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='FlavorImage',
        ),
    ]
