# Generated by Django 5.0 on 2024-01-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_test_remove_flavorimage_flavor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FlavorImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='flavors/%y/%m/%d')),
                ('type', models.CharField(max_length=50)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.flavor')),
            ],
        ),
        migrations.CreateModel(
            name='FlavorToProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.flavor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='flavor',
            name='product',
            field=models.ManyToManyField(through='ecom.FlavorToProduct', to='ecom.product'),
        ),
    ]
