# Generated by Django 5.0 on 2024-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_flavor_flavorimage_flavortoproduct_delete_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total',
            new_name='price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='flavor',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='serving',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
