# Generated by Django 5.0 on 2024-01-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_contactinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='fullnam',
            new_name='fullname',
        ),
    ]
