# Generated by Django 5.0 on 2024-01-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_rename_total_cartitem_price_cartitem_flavor_and_more'),
        ('ecom', '0012_rename_fullnam_contactinfo_fullname'),
    ]

    operations = [
    ]
