# Generated by Django 5.0 on 2024-01-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_merge_20240112_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
