# Generated by Django 5.0 on 2024-01-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_order_total_ordertoproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
